openapi: 3.0.0

info:
  title: Account Profile
  version: "1.0"
  description: "This APIs describe how OBC system communicate with NBC gateway"

servers: # context path - /api/v1
  - url: http://localhost:8080
    description: Local development server

paths:
  /init-link-account:
    post:
      summary: Initialize CASA linking account
      description: Link CASA between NBC and GoWave
      operationId: initLinkAccount
      requestBody:
        description: Create account
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitAccountRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitAccountResponse'
        '400':
          description: Invalid Account ID
        '404':
          description: Account not found
        '405':
          description: Validation exception

components:
  schemas:
    ResponseWrapper:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/ResponseStatus'

    ResponseStatus:
      type: object
      properties:
        code:
          type: integer
          example: 10
        errorCode:
          type: string
          example: 001
        errorMessage:
          type: string
          example: account_not_found

    InitAccountRequest:
      type: object
      properties:
        loginType:
          type: string
          enum:
            - PHONE_PIN
            - USER_PWD
          example: PHONE_PIN
        login:
          type: string
          example: john789
        key:
          type: string
          description: A hash password in SHA256
          example: hash_password
        bakongAccId:
          type: string
          example: john@email.com
        phoneNumber:
          type: string
          example: '09827923472'

    InitAccountResponse:
      allOf:
        - $ref: '#/components/schemas/ResponseWrapper'
        - type: object
          properties:
            data:
              type: object
              description: Account Response
              properties:
                accessToken:
                  type: string
                  example: jwt_token
                requireOtp:
                  type: integer
                  example: 1
                requireChangePhone:
                  type: integer
                  example: 0
                last3DigitsPhone:
                  type: string
                  example: 123

    AccountModel:
      type: object
      description: Account model
      properties:
        id:
          type: integer
        bakongId:
          type: string
        accountId:
          type: string
        active:
          type: boolean

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: security scheme type (HTTP bearer)
