openapi: 3.0.0

info:
  title: Open Banking Client
  version: "1.0"
  description: "Those APIs describe how OBC system communicate with NBC gateway"

tags:
  - name: Account
    description: Account
  - name: System Exchange
    description: User Profile Exchange from GoWave
  - name: Transaction
    description: Account Transaction
  - name: Scheduler
    description: Scheduler jobs

servers: # context path - /api/v1
  - url: http://localhost:8080
    description: Local development server

paths:
  /init-link-account:
    $ref: './paths/init-link-account.yml'
  /verify-otp:
    $ref: './paths/verify-otp.yml'
  /finish-link-account:
    $ref: './paths/finish-link-account.yml'
  /unlink-account:
    $ref: './paths/unlink-account.yml'
  /authenticate:
    $ref: './paths/authenticate.yml'
  /account-detail:
    $ref: './paths/account-detail.yml'
  /init-transaction:
    $ref: './paths/init-transaction.yml'
  /finish-transaction:
    $ref: './paths/finish-transaction.yml'
  /account-transactions:
    $ref: './paths/account-transactions.yml'
  /gw/user-exchange:
    $ref: './paths/user-exchange.yml'
  /gw/login:
    $ref: './paths/gw-login.yml'
  /transaction-processing:
    $ref: './paths/transaction-processing.yml'
  /scheduler:
    $ref: './paths/scheduler-job.yml'

components:
  schemas:
    ResponseWrapper:
      $ref: './schemas/common/ResponseWrapper.yml'
    ResponseStatus:
      $ref: './schemas/common/ResponseStatus.yml'
    InitAccountRequest:
      $ref: './schemas/account/InitAccountRequest.yml'
    InitAccountResponse:
      $ref: './schemas/account/InitAccountResponse.yml'
    VerifyOtpRequest:
      $ref: './schemas/account/VerifyOtpRequest.yml'
    VerifyOtpResponse:
      $ref: './schemas/account/VerifyOtpResponse.yml'
    FinishLinkAccountRequest:
      $ref: './schemas/account/FinishLinkAccountRequest.yml'
    FinishLinkAccountResponse:
      $ref: './schemas/account/FinishLinkAccountResponse.yml'
    UnlinkAccountRequest:
      $ref: './schemas/account/UnlinkAccountRequest.yml'
    UnlinkAccountResponse:
      $ref: './schemas/account/UnlinkAccountResponse.yml'
    FinishTransactionRequest:
      $ref: './schemas/transaction/FinishTransactionRequest.yml'
    FinishTransactionResponse:
      $ref: './schemas/transaction/FinishTransactionResponse.yml'
    AuthenticationRequest:
      $ref: './schemas/account/AuthenticationRequest.yml'
    AuthenticationResponse:
      $ref: './schemas/account/AuthenticationResponse.yml'
    GetAccountDetailRequest:
      $ref: './schemas/account/GetAccountDetailRequest.yml'
    GetAccountDetailResponse:
      $ref: './schemas/account/GetAccountDetailResponse.yml'
    InitTransactionRequest:
      $ref: './schemas/transaction/InitTransactionRequest.yml'
    InitTransactionResponse:
      $ref: './schemas/transaction/InitTransactionResponse.yml'
    GetAccountTransactionsRequest:
      $ref: './schemas/transaction/GetAccountTransactionsRequest.yml'
    GetAccountTransactionsResponse:
      $ref: './schemas/transaction/GetAccountTransactionsResponse.yml'
    ExchangeAccountRequest:
      $ref: './schemas/user/UserExchangeRequest.yml'
    ExchangeAccountResponse:
      $ref: './schemas/user/UserExchangeResponse.yml'
    GWAuthenticationRequest:
      $ref: './schemas/user/GWAuthenticationRequest.yml'
    GWAuthenticationResponse:
      $ref: './schemas/user/GWAuthenticationResponse.yml'
    AccountModel:
      $ref: './schemas/account/AccountModel.yml'
    AccountFilterCondition:
      $ref: './schemas/account/AccountFilterCondition.yml'
    UserModel:
      $ref: './schemas/user/UserModel.yml'
    TransactionModel:
      $ref: './schemas/transaction/TransactionModel.yml'
    TransactionHistoryModel:
      $ref: './schemas/transaction/TransactionHistoryModel.yml'
    PGAuthRequest:
      $ref: './schemas/pg/PGAuthRequest.yml'
    PGAuthResponse:
      $ref: './schemas/pg/PGAuthResponse.yml'
    PGProfileResponse:
      $ref: './schemas/pg/PGProfileResponse.yml'
    InfoBipSendOtpRequest:
      $ref: './schemas/infoBip/InfoBipSendOtpRequest.yml'
    InfoBipSendOtpResponse:
      $ref: './schemas/infoBip/InfoBipSendOtpResponse.yml'
    InfoBipVerifyOtpRequest:
      $ref: './schemas/infoBip/InfoBipVerifyOtpRequest.yml'
    InfoBipVerifyOtpResponse:
      $ref: './schemas/infoBip/InfoBipVerifyOtpResponse.yml'
    InfoBipLoginResponse:
      $ref: './schemas/infoBip/InfoBipLoginResponse.yml'
    CDRBLoginRequest:
      $ref: './schemas/cdrb/CDRBLoginRequest.yml'
    CDRBLoginResponse:
      $ref: './schemas/cdrb/CDRBLoginResponse.yml'
    CDRBGetHsmKeyResponse:
      $ref: './schemas/cdrb/CDRBGetHsmKeyResponse.yml'
    CDRBGetAccountDetailRequest:
      $ref: './schemas/cdrb/CDRBGetAccountDetailRequest.yml'
    CDRBGetAccountDetailResponse:
      $ref: './schemas/cdrb/CDRBGetAccountDetailResponse.yml'
    CDRBFeeAndCashbackRequest:
      $ref: './schemas/cdrb/CDRBFeeAndCashbackRequest.yml'
    CDRBFeeAndCashbackResponse:
      $ref: './schemas/cdrb/CDRBFeeAndCashbackResponse.yml'
    CDRBTransferRequest:
      $ref: './schemas/cdrb/CDRBTransferRequest.yml'
    CDRBTransferResponse:
      $ref: './schemas/cdrb/CDRBTransferResponse.yml'
    CDRBTransferInquiryRequest:
      $ref: './schemas/cdrb/CDRBTransferInquiryRequest.yml'
    CDRBTransferInquiryResponse:
      $ref: './schemas/cdrb/CDRBTransferInquiryResponse.yml'
    CDRBTransactionHistoryRequest:
      $ref: './schemas/cdrb/CDRBTransactionHistoryRequest.yml'
    CDRBTransactionHistoryResponse:
      $ref: './schemas/cdrb/CDRBTransactionHistoryResponse.yml'
    SchedulerJobRequest:
      $ref: './schemas/scheduler/JobRequest.yml'
    SFTPConfig:
      $ref: './schemas/config/SFTPConfig.yml'
    SIBSSyncDateConfig:
      $ref: './schemas/config/SIBSSyncDateConfig.yml'
    TransactionBatchFileProcessingRequest:
      $ref: './schemas/transaction/TransactionBatchFileProcessingRequest.yml'
    BatchReportStatus:
      $ref: './schemas/transaction/BatchReportStatus.yml'
    JobNameEnum:
      $ref: './schemas/scheduler/JobNameEnum.yml'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: security scheme type (HTTP bearer)
