openapi: 3.0.0

info:
  title: Open Banking Client
  version: "1.0"
  description: "Those APIs describe how OBC system communicate with NBC gateway"

tags:
  - name: Account
    description: Account
  - name: UserProfile
    description: User profile
  - name: UserExchange
    description: User exchange

servers: # context path - /api/v1
  - url: http://localhost:8080
    description: Local development server

paths:
  /init-link-account:
    $ref: './paths/init-link-account.yml'
  /verify-otp:
    $ref: './paths/verify-otp.yml'
  /finish-link-account:
    $ref: './paths/finish-link-account.yml'
  /authenticate:
    $ref: './paths/authenticate.yml'
  /account-detail:
    $ref: './paths/account-detail.yml'
  /gw/user-exchange:
    $ref: './paths/user-exchange.yml'
  /gw/login:
    $ref: './paths/gw-login.yml'

components:
  schemas:
    ResponseWrapper:
      $ref: './schemas/common/ResponseWrapper.yml'
    ResponseStatus:
      $ref: './schemas/common/ResponseStatus.yml'
    InitAccountRequest:
      $ref: './schemas/account/InitAccountRequest.yml'
    InitAccountResponse:
      $ref: './schemas/account/InitAccountResponse.yml'
    VerifyOtpRequest:
      $ref: './schemas/account/VerifyOtpRequest.yml'
    VerifyOtpResponse:
      $ref: './schemas/account/VerifyOtpResponse.yml'
    FinishLinkAccountRequest:
      $ref: './schemas/account/FinishLinkAccountRequest.yml'
    FinishLinkAccountResponse:
      $ref: './schemas/account/FinishLinkAccountResponse.yml'
    AuthenticationRequest:
      $ref: './schemas/account/AuthenticationRequest.yml'
    AuthenticationResponse:
      $ref: './schemas/account/AuthenticationResponse.yml'
    GetAccountDetailRequest:
      $ref: './schemas/account/GetAccountDetailRequest.yml'
    GetAccountDetailResponse:
      $ref: './schemas/account/GetAccountDetailResponse.yml'
    ExchangeAccountRequest:
      $ref: './schemas/user/UserExchangeRequest.yml'
    ExchangeAccountResponse:
      $ref: './schemas/user/UserExchangeResponse.yml'
    GWAuthenticationRequest:
      $ref: './schemas/user/GWAuthenticationRequest.yml'
    GWAuthenticationResponse:
      $ref: './schemas/user/GWAuthenticationResponse.yml'
    AccountModel:
      $ref: './schemas/account/AccountModel.yml'
    UserModel:
      $ref: './schemas/user/UserModel.yml'
    PGAuthRequest:
      $ref: './schemas/pg/PGAuthRequest.yml'
    PGAuthResponse:
      $ref: './schemas/pg/PGAuthResponse.yml'
    PGProfileResponse:
      $ref: './schemas/pg/PGProfileResponse.yml'
    InfoBipVerifyOtpResponse:
      $ref: './schemas/infoBip/InfoBipVerifyOtpResponse.yml'
    CDRBLoginRequest:
      $ref: './schemas/cdrb/CDRBLoginRequest.yml'
    CDRBLoginResponse:
      $ref: './schemas/cdrb/CDRBLoginResponse.yml'
    CDRBGetHsmKeyResponse:
      $ref: './schemas/cdrb/CDRBGetHsmKeyResponse.yml'

    CdrbGetHmsKeyResponse:
      $ref: './schemas/cdrb/CdrbGetHmsKeyResponse.yml'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: security scheme type (HTTP bearer)
