openapi: 3.0.0

info:
  title: Open Banking Client
  version: "1.0"
  description: "Those APIs describe how OBC system communicate with NBC gateway"

tags:
  - name: Account
    description: Account
  - name: UserProfile
    description: User profile
  - name: UserExchange
    description: User exchange

servers: # context path - /api/v1
  - url: http://localhost:8080
    description: Local development server

paths:
  /init-link-account:
    $ref: './paths/init-link-account.yml'
  /gw/user-exchange:
    $ref: './paths/user-exchange.yml'
  /gw/login:
    $ref: './paths/gw-login.yml'

components:
  schemas:
    ResponseWrapper:
      $ref: './schemas/common/ResponseWrapper.yml'
    ResponseStatus:
      $ref: './schemas/common/ResponseStatus.yml'
    InitAccountRequest:
      $ref: './schemas/account/InitAccountRequest.yml'
    InitAccountResponse:
      $ref: './schemas/account/InitAccountResponse.yml'
    ExchangeAccountRequest:
      $ref: './schemas/user/UserExchangeRequest.yml'
    ExchangeAccountResponse:
      $ref: './schemas/user/UserExchangeResponse.yml'
    GWAuthenticationRequest:
      $ref: './schemas/user/GWAuthenticationRequest.yml'
    GWAuthenticationResponse:
      $ref: './schemas/user/GWAuthenticationResponse.yml'
    AccountModel:
      $ref: './schemas/account/AccountModel.yml'
    UserModel:
      $ref: './schemas/user/UserModel.yml'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: security scheme type (HTTP bearer)
