INSERT INTO obc.tbl_obc_config
(config_key, config_value, created_date, updated_date, updated_by)
VALUES
('CDRB_URL', JSON_OBJECT('value', 'https://api.dev.cdrb.link'), CURRENT_TIMESTAMP, NULL, 'OBC_SYSTEM'),
('CDRB_ACCOUNT', JSON_OBJECT('username', 'sorrynext', 'password', '0XJAoQ/DZuV6GC+/sjMgUg==', 'aesKey', '1234567812345678', 'aesIv', 'p9ozxmiejwPGaWdJ/ffzqA=='), CURRENT_TIMESTAMP, NULL, 'OBC_SYSTEM'),
('CDRB_HSM_ZMK', JSON_OBJECT('value', '5497B691458FC1CD31A16116701F57F8'), CURRENT_TIMESTAMP, NULL, 'OBC_SYSTEM'),
('CDRB_HSM_IV', JSON_OBJECT('value', '0000000000000000'), CURRENT_TIMESTAMP, NULL, 'OBC_SYSTEM'),
('CDRB_X_API_KEY', JSON_OBJECT('value', 'NQrIN7HPBt141uX5yw2SZ4NigpagyHkZ8cG9b2rf'), CURRENT_TIMESTAMP, NULL, 'OBC_SYSTEM'),
('PG1_ACCOUNT', JSON_OBJECT('username', 'soap_user', 'password', '+66xZ_feBcRpYP9e'), CURRENT_TIMESTAMP, NULL, 'OBC_SYSTEM'),
('PG1_URL', JSON_OBJECT('value', 'http://10.202.38.27/'), CURRENT_TIMESTAMP, NULL, 'OBC_SYSTEM'),
('REQUIRED_INIT_ACCOUNT_OTP', JSON_OBJECT('value', 1), CURRENT_TIMESTAMP, NULL, 'OBC_SYSTEM'),
('TRANSACTION_CONFIG', JSON_OBJECT('txMinAmt', 10, 'txMaxAmt', 10.000, 'defaultCcy', 'USD', 'requiredTrxOtp', 0), CURRENT_TIMESTAMP, NULL, 'OBC_SYSTEM');