spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none #create, create-drop, validate, update, none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:33060/obc?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1qaz!QAZ}
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    enabled: true
    change-log: classpath:/liquibase/uat-changelog.xml

  application:
    name: ${APP_NAME:obc-uat}

#logging:
#  level:
#    web: debug

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  jwt-secret: ${JWT_SECRET_KEY:my-secret}

server:
  port: 8081