spring:
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    show-sql: true

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:33068}/obc?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1qaz!QAZ}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimumIdle: ${SPRING_HIKARI_MIN_IDLE:2}
      maximumPoolSize: ${SPRING_HIKARI_MAX_POOL_SIZE:20}
      idleTimeout: ${SPRING_HIKARI_IDLE_TIMEOUT:120000}
      connectionTimeout: ${SPRING_HIKARI_CONNECTION_TIMEOUT:300000}
      leakDetectionThreshold: ${SPRING_HIKARI_LEAK_DETECTION_THRESHOLD:300000}

  flyway:
    locations: classpath:sql/ddl,classpath:sql/dml

  jackson:
    default-property-inclusion: ALWAYS

  quartz:
    job-store-type: jdbc

  application:
    name: ${APP_NAME:obc-sit}

logging:
  level:
    web: debug

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/v1}
  ssl:
    enabled: ${SSL_ENABLE:false}
    key-store-type: ${KEY_STORE_TYPE:JKS}
    key-store: ${KEY_STORE_PATH:"PATH_TO_KEY_STORE_JKS_FILE"}
    key-store-password: ${KEY_STORE_PASSWORD:"KEY_STORE_PASSWORD"}
    enabled-protocols: ${ENABLED_PROTOCOLS_VERSION:TLSv1.2}
    protocol: TLS
obc:
  gowave-user: ${OBC_GOWAVE_USER:gowave_user}
  gowave-password: ${OBC_GOWAVE_PASSWORD:gowave_password}
  security:
    jwt-secret: ${JWT_SECRET:my-secret}
    jwt-ttl: ${JWT_TTL:300}
    aesKey: ${CDRB_AES_KEY:64e80a9de98bff0c9ac865d2fa381611}
    aesIv: ${CDRB_AES_IV:TzwQBXz8dGHQCEjEwppfiQ==}
  pg1:
    url: http://10.202.38.24
    username: ${PG1_USERNAME:soap_user}
    password: ${PG1_PASSWORD:+2023xZ_feBcRpYP9e}
  cdrb:
    url: https://api.uat2.cdrb.link
    username: ${CDRB_USERNAME:obc_uat2}
    password: ${CDRB_PASSWORD:wQMeJRLjQK5JlbZ1eovTng==}
    hsmZmk: ${CDRB_HSM_ZMK:807097B901C7BC0D70C72C6892E094B6}
    xApiKey: ${CDRB_X_API_KEY:SoeLsIrogq92fh3VHermr3MyjW0OGRyF1zQjmwaP}
  infobip:
    url: https://9rd19r.api.infobip.com
    appId: AEBF567DD1E525DFE30EB18DDB20D90B
    messageId: 08618DC7FE0B5574F8BE47E9452D776B
    username: bakong_link_casa
    password: Thakvika@081
    ncNeeded: ${INFOBIP_NC_NEEDED:false}
    init-link-required-opt: ${INIT_LINK_REQUIRED_OTP:true}
    init-transger-required-opt: ${INIT_TRANSFER_REQUIRED_OTP:true}
    pin-time-to-live-in-mins: ${PIN_TIME_TO_LIVE_IN_MINS:2}
  sftp:
    username: ${SFTP_USERNAME:testuser}
    password: ${SFTP_PASSWORD:testpassword}
    host: ${SFTP_HOST:127.0.0.1}
    port: ${SFTP_PORT:2022}
    path: ${SFTP_PATH:data}
  rate-limits:
    enabled: ${RATE_LIMIT_ENABLED:true}
    bandwidths:
      capacity: ${RATE_LIMIT_BANDWIDTHS_CAPACITY:200}
      period: ${RATE_LIMIT_BANDWIDTHS_PERIOD_IN_MINUTE:1}

config:
  maxStackTraceLength: ${MAX_STACK_TRACE_LENGTH:19999}
  allWatchToken: ${ALL_WATCH_TOKEN:ALL_WATCH_TOKEN}

