spring:
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    show-sql: false

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/obc?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1qaz!QAZ}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimumIdle: ${SPRING_HIKARI_MIN_IDLE:2}
      maximumPoolSize: ${SPRING_HIKARI_MAX_POOL_SIZE:20}
      idleTimeout: ${SPRING_HIKARI_IDLE_TIMEOUT:120000}
      connectionTimeout: ${SPRING_HIKARI_CONNECTION_TIMEOUT:300000}
      leakDetectionThreshold: ${SPRING_HIKARI_LEAK_DETECTION_THRESHOLD:300000}

  flyway:
    locations: classpath:sql/ddl,classpath:sql/dml
    clean-on-validation-error: true

  jackson:
    default-property-inclusion: NON_NULL

  application:
    name: ${APP_NAME:obc-sit}

logging:
  level:
    web: debug

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  port: ${SERVER_PORT:8089}
  servlet:
    context-path: /api/v1

app:
  jwt-secret: my-secret